// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYFQnV-bzNSVXTVoa7pa-IZFJXbU_csA',
    appId: '1:709063332630:web:c460363abbefbb56e1f637',
    messagingSenderId: '709063332630',
    projectId: 'hubo-64b8c',
    authDomain: 'hubo-64b8c.firebaseapp.com',
    storageBucket: 'hubo-64b8c.appspot.com',
    measurementId: 'G-PV59QH554F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmx4F64236I76JrbtTX-cGMHWBI1vijU',
    appId: '1:709063332630:android:f04ed390df0a3f7ce1f637',
    messagingSenderId: '709063332630',
    projectId: 'hubo-64b8c',
    storageBucket: 'hubo-64b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm5pkmB0U_3m7fZfgZhWIZFpJa8xk6Jt8',
    appId: '1:709063332630:ios:ecebceee8f44e363e1f637',
    messagingSenderId: '709063332630',
    projectId: 'hubo-64b8c',
    storageBucket: 'hubo-64b8c.appspot.com',
    iosClientId: '709063332630-h25pd7br5v1lr4u30m3hiq9qls5ajjvt.apps.googleusercontent.com',
    iosBundleId: 'fr.palama.hubo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm5pkmB0U_3m7fZfgZhWIZFpJa8xk6Jt8',
    appId: '1:709063332630:ios:dc58ccbac7d2d565e1f637',
    messagingSenderId: '709063332630',
    projectId: 'hubo-64b8c',
    storageBucket: 'hubo-64b8c.appspot.com',
    iosClientId: '709063332630-4c00dk3f17ub000m6s4fefqvak89d6lh.apps.googleusercontent.com',
    iosBundleId: 'fr.palama.hubo.RunnerTests',
  );
}
